---
gateway: 10.0.0.138

vms:
  backupserver:
    ip: 100.80.220.101
  services:
    ip: 10.0.0.44
    vmid: 4001
  subnet_router:
    ip: 10.0.0.78
  samba:
    ip: 10.0.0.79
  immich:
    ip: 10.0.0.80
  github_runner:
    ip: 10.0.0.81
  pihole-secondary:
    ip: 10.0.0.82
  pihole-docker-test:
    ip: 10.0.0.86
  loki:
    ip: 10.0.0.44
  grafana:
    ip: 10.0.0.44
  subnet-router-secondary:
    ip: 10.0.0.85
    vmid: 4009

template:
  name: alma-96-cloud-template-automated
  vmid: 9000
  user: haaksk

proxmox:
  ip: 10.0.0.41
  api_user: root@pam
  user: root
  node: proxmox

proxmox2:
  ip: 10.0.0.33
  api_user: root@pam
  user: root
  node: proxmox2

virtiofs_tags:
  smb: smb
