---
- name: Ensure the update script directory exists
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: "0755"

- name: Create the update script
  ansible.builtin.copy:
    dest: /usr/local/bin/update_packages.sh
    content: |
      #!/bin/bash
      sudo yum update -y
    mode: "0755"

- name: Add a cron job to run the update script weekly as root
  ansible.builtin.cron:
    name: "Weekly package updates"
    job: "/usr/local/bin/update_packages.sh"
    user: root
    weekday: "0" # Sunday
    hour: "3" # 3 AM
    minute: "0"
