---
- name: Check if jellyfin config directory exists
  ansible.builtin.stat:
    path: "{{ jellyfin_dir }}/config"
  register: jellyfin_config_exists

- name: Restore jellyfin config if missing
  ansible.builtin.include_tasks: restore.yml
  when: not jellyfin_config_exists.stat.exists

- name: Install jellyfin
  ansible.builtin.import_tasks: jellyfin.yml
