- name: Backup services before any changes
  hosts: services
  become: true
  gather_facts: false
  vars_files:
    - ../../secrets.yml
  tasks:
    - name: Take backup of syncthing config
      ansible.builtin.include_role:
        name: syncthing
        tasks_from: backup.yml
      when: force_recreate | default(false) | bool

    - name: Take backup of uptimekuma
      ansible.builtin.include_role:
        name: uptimekuma
        tasks_from: backup.yml
      when: force_recreate | default(false) | bool

    - name: Take backup of current couchdb
      ansible.builtin.include_role:
        name: couchdb
        tasks_from: backup.yml
      when: force_recreate | default(false) | bool

    - name: Take backup of vaultwarden database
      ansible.builtin.include_role:
        role: vaultwarden_backup
        tasks_from: backup.yml
      when: force_recreate | default(false) | bool

    - name: Take backup of grafana
      ansible.builtin.include_role:
        name: grafana
        tasks_from: backup.yml
      when: force_recreate | default(false) | bool

- name: Create services VM
  hosts: proxmox
  become: false
  vars_files:
    - ../../secrets.yml
  vars:
    newid: "{{ vms.services.vmid }}"
    ipaddr: "{{ vms.services.ip }}"
  roles:
    - role: create_vm
      vars:
        create_vm_name: services
        create_vm_newid: "{{ vms.services.vmid }}"
        create_vm_ipaddr: "{{ vms.services.ip }}"
        create_vm_balloon: 5000
        create_vm_cores: 3
        create_vm_memory: 18000
        create_vm_sockets: 1
        create_vm_disk_size: 100G
        create_vm_virtiofs_tag: "{{ virtiofs_tags.smb }}"

- name: Configure services
  hosts: services
  become: true
  vars_files:
    - ../../secrets.yml
  vars:
    docker_auto_update_compose_paths:
      - "/home/{{ template.user }}/nebula-sync/docker-compose.yml"
      - "/home/{{ template.user }}/couchdb/docker-compose.yml"
      - "/home/{{ template.user }}/caddy/docker-compose.yml"
      - "/home/{{ template.user }}/vaultwarden/docker-compose.yml"
      - "/home/{{ template.user }}/uptimekuma/docker-compose.yml"
      - "/home/{{ template.user }}/loki/docker-compose.yml"
      - "/home/{{ template.user }}/grafana/docker-compose.yml"
    promtail_docker_installed: true
  roles:
    - scheduled_update
    - scheduled_reboot
    - firewall
    - pihole_health
    - nebula_sync
    - syncthing
    - couchdb
    - couchdb_backup
    - docker_auto_update
    - promtail
    - echovault
    - caddy
    - aultwarden
    - vaultwarden_backup
    - uptimekuma
    - role: loki
      tags: loki
    - role: grafana
      tags: grafana