---
- name: Create Docker volume for Portainer
  community.docker.docker_volume:
    name: portainer_data
    state: present

- name: Run Portainer container
  community.docker.docker_container:
    name: portainer
    image: portainer/portainer-ce:lts
    state: started
    restart_policy: always
    published_ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

# stop and start portainer, sometimes I've needed to to this
- name: Ensure Portainer container is stopped
  community.docker.docker_container:
    name: portainer
    state: stopped

- name: Ensure Portainer container is started
  community.docker.docker_container:
    name: portainer
    state: started
