---
- name: create app folder
  ansible.builtin.file:
    path: /home/haaksk/jellyfin
    state: directory
    mode: '0755'

- name: make sure haaksk is in sambausers group
  ansible.builtin.user:
    name: haaksk
    groups: sambausers
    append: yes

- name: create jellyfin dirs
  ansible.builtin.file:
    path: /home/haaksk/jellyfin
    state: directory
    mode: '0755'
    owner: haaksk
    group: sambausers
    recurse: true
  loop:
    - /home/haaksk/jellyfin/cache
    - /home/haaksk/jellyfin/config

- name: Copy docker-compose.yml to app folder
  ansible.builtin.copy:
    dest: /home/haaksk/jellyfin/docker-compose.yml
    content: |

      services:
        jellyfin:
          image: jellyfin/jellyfin
          container_name: jellyfin
          user: 1000:1001
          network_mode: 'host'
          volumes:
            - /home/haaksk/jellyfin/config:/config:Z
            - /home/haaksk/jellyfin/cache:/cache:Z
            - type: bind
              source: /mnt/storage/smb/gcn+
              target: /media/gcn
            - type: bind
              source: /mnt/storage/smb/Movies
              target: /media/movies
          restart: 'unless-stopped'


- name: stop 
  community.docker.docker_compose_v2:
    project_src: /home/haaksk/jellyfin
    state: absent

- name: run docker compose up -d
  community.docker.docker_compose_v2: 
    project_src: /home/haaksk/jellyfin
  register: output

- name: open firewall
  ansible.builtin.firewalld: 
    port: 8096/tcp
    state: enabled
    permanent: true
    immediate: true
