---
- name: Clone and Configure Proxmox VM
  hosts: proxmox
  gather_facts: false
  vars_files:
    - ../common/secrets.yml
  tasks:
    # --- venv tasks remain the same ---
    - name: Ensure Python 3 and venv are installed (if running on PVE node)
      ansible.builtin.package:
        name:
          - python3
          - python3-venv
        state: present
      become: true
      when: inventory_hostname == 'proxmox' 

    - name: Create a Python virtual environment for Ansible (if running on PVE node)
      ansible.builtin.command:
        cmd: python3 -m venv /opt/ansible_venv
        creates: /opt/ansible_venv
      become: true
      when: inventory_hostname == 'proxmox' 

    - name: Ensure proxmoxer and requests libraries are installed in the venv (if running on PVE node)
      ansible.builtin.command:
        cmd: /opt/ansible_venv/bin/pip install proxmoxer requests
        creates: /opt/ansible_venv/lib/python3.*/site-packages/proxmoxer
      become: true
      when: inventory_hostname == 'proxmox' 

    - name: Set the Python interpreter (if running on PVE node)
      set_fact:
        ansible_python_interpreter: /opt/ansible_venv/bin/python3
      when: inventory_hostname == 'proxmox' 

    # --- Task to Clone and Configure ---
    - name: Clone VM 
      community.general.proxmox_kvm:
        # --- Connection ---
        api_host: 10.0.0.41
        api_user: root@pam
        api_token_id: ansible-automation
        api_token_secret: "{{ pve_api_token_secret }}"
        node: proxmox

        # --- Clone Operation ---
        clone: "alma-template"
        vmid: 9003              # Source VM ID
        name: "fileserver-test2"
        newid: 4003              # Target VM ID
        full: yes                 # Create a full clone

        # --- Target VM State ---
        state: present            # Ensure VM exists
        description: "Fileserver VM created with Ansible"

        # --- Hardware ---
        balloon: 500
        cores: 2
        memory: 4096
        numa_enabled: 1
        sockets: 1
        onboot: 1

  #  # --- Task to add virtiofs0 using qm set ---
  #  - name: Set virtiofs0 configuration using qm command
  #    ansible.builtin.command:
  #      # Use qm set <vmid> --option 'value'
  #      cmd: qm set 4003 --virtiofs0 'smb,expose-xattr=1'
  #    changed_when: true #

    - name: Change ip
      ansible.builtin.command:
        cmd: qm set 4003 --ipconfig0 ip=10.0.0.57/24,gw=10.0.0.138

