---
- name: Clone and Configure Proxmox VM
  hosts: proxmox # Run on the control node, connect to PVE API
  gather_facts: false
  vars_files:
    - ../common/secrets.yml
  tasks:
    - name: Ensure Python 3 and venv are installed
      ansible.builtin.package:
        name: 
          - python3
          - python3-venv
        state: present
      become: true

    - name: Create a Python virtual environment for Ansible
      ansible.builtin.command:
        cmd: python3 -m venv /opt/ansible_venv
        creates: /opt/ansible_venv
      become: true

    - name: Ensure proxmoxer and requests libraries are installed in the virtual environment
      ansible.builtin.command:
        cmd: /opt/ansible_venv/bin/pip install proxmoxer requests
      become: true

    - name: Set the Python interpreter to use the virtual environment
      set_fact:
        ansible_python_interpreter: /opt/ansible_venv/bin/python3

    - name: Clone VM with source vmid and target newid with specified settings
      community.general.proxmox_kvm:
        api_host: 10.0.0.41
        api_user: root@pam
        api_token_id: ansible-automation
        api_token_secret: "{{ pve_api_token_secret }}"
        clone: "vm-9000"
        vmid: 9000
        newid: 4000
        name: "fileserver-44"
        node: proxmox
        balloon: 0
        boot: "c"
        bootdisk: "scsi0"
        cipassword: "$5$yOaMe4Tr$aeWDPKsA0ehkzsGQZrSzfLu4pgtcHi291.0xvuWTHvD"
        ciuser: "haaksk"
        cores: 4
        cpu: "host"
        memory: 4096
        nameserver: "148.122.164.253"
        numa: 1
        onboot: 1
        scsihw: "virtio-scsi-pci"
        searchdomain: "telenor.net"
        smbios1: "uuid=4a06fa63-777b-4423-84d4-13b9235d5671"
        sockets: 2
        sshkeys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzyMriPvf6XXxG+CGV7swMOr2LgKORsnXUiBlQQHN/Bqu6Mx9WTyr/DvFu3yvUYyFH5+BS1zZ6IZObw7bFwbfTevaMuiv1tPOu50ygP8Vz2A5UhvjDgX5o/n2W3o1e3oVxY6RKnF0jE/mIOynT9H0BHWPz82QZq1+YfrkcUV1D9pSFx696ksWauKxUyFcSvyd4y9aBoFO8plbffwgS4d6qArfCn9whSLqueWRJ2i4+Hd+16zvHBuAoESl192QBWXpvtOU2JM3paS+9KKOFMMZqbJfqMS0tmWFbnwz4kCCQMP/E1FyzgcyQg7JG/m2KktSZ+gfuP0rWVjL2wjZMUODkwCFZ+h+FiozBoL6v1EEenEllze5CwGUgOXgJR7w70eOOL8FvVBeAIj67HnouWoPgSGDdSRM3+a+dglxSQIm+kIw8NorRe0/RtlxHmF3KvSrU2xjjMebEAxlK6LNALUZLww9r6n56fTDUgiir1lXQxkfcNROT0w0cKTU1Vxi/seGwTwPEaWJlnLOXyIUOB+NKJqhrhWGjqSzK7RIFvlXVHULVvhNQfjescZuUGPh5Mosah3LKmL1B6W58yLbk/QHoKb/RKRIAExqPRHrP4mEyaVYlBnxlrWHbW9ESdKrElAfmpNHQ/dRT9ZiGWkxzV/YIiHPAsFMYCu+5MypcrCq6wQ== haaksk@gmail.com"
        tablet: 0
        template: 1
        vga: "serial0"
        vmgenid: "84bf44ce-d174-4738-951b-adb15f7bfa96"
        description: "Fileserver VM created with Ansible"
        net0: "virtio=BC:24:11:B5:30:A8,bridge=vmbr0"
        serial0: "socket"
        ssd: 1
        full: yes
