---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart uptimekuma
  ansible.builtin.shell:
    cmd: docker compose up -d
    chdir: "{{ uptimekuma_data_dir | dirname }}"
