---
- name: Ensure Caddy directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ caddy_dir }}"
    owner: "{{ template.user }}"
    group: "{{ template.user }}"
    mode: "0755"

- name: Copy Caddy Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ caddy_dir }}/docker-compose.yml"
    owner: "{{ template.user }}"
    group: "{{ template.user }}"
    mode: "0755"
  notify: Restart caddy

- name: Copy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ caddy_dir }}/Caddyfile"
    owner: "{{ template.user }}"
    group: "{{ template.user }}"
    mode: "0755"
  notify: Restart caddy

- name: Open Caddy firewall port
  ansible.posix.firewalld:
    port: "{{ caddy_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
  become: true

- name: Start Caddy
  community.docker.docker_compose_v2:
    project_src: "{{ caddy_dir }}"
  register: caddy_compose_result
