---
- name: Read CouchDB vars to get port
  ansible.builtin.include_vars:
    file: "../../couchdb/defaults/main.yml"

- name: Read Vaultwarden vars to get port
  ansible.builtin.include_vars:
    file: "../../vaultwarden/defaults/main.yml"

- name: Set up Caddy
  ansible.builtin.include_tasks: caddy.yml
