---
- name: read couchdb vars to get port
  ansible.builtin.include_vars:
      file: "../../couchdb/defaults/main.yml"

- name: read vaultwarden vars to get port
  ansible.builtin.include_vars:
    file: "../../vaultwarden/defaults/main.yml"

- name: setup caddy
  ansible.builtin.include_tasks: caddy.yml
