---
- name: Restore couchdb backup if available
  ansible.builtin.import_tasks: restore.yml

- name: Install couchdb
  ansible.builtin.import_tasks: couchdb.yml

- name: Setup couchdb backup
  ansible.builtin.import_tasks: couchdb_backup.yml
