- name: Ensure prerequisites are installed (ca-certificates, curl)
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: true

- name: Create Docker keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.shell:
    cmd: curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    creates: /etc/apt/keyrings/docker.asc
  changed_when: true

- name: Set appropriate permissions for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: 'a+r'

- name: Add the Docker APT repository
  ansible.builtin.shell:
    cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    creates: /etc/apt/sources.list.d/docker.list
  changed_when: true

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Add user to the docker group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: docker
    append: true