# roles/pihole_almalinux/handlers/main.yml
---
- name: Restart pihole-FTL
  ansible.builtin.service:
    name: pihole-FTL
    state: restarted

- name: Restart network manager
  ansible.builtin.service:
    name: NetworkManager
    state: restarted


- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Reboot server
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for SELinux state change"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami