---
- name: Install and Configure Docker CE
  hosts: immich
  become: true
  vars:
    user: haaksk

  tasks:
    - name: Ensure prerequisites are installed (yum-utils)
      ansible.builtin.dnf:
        name: yum-utils
        state: present
        update_cache: true

    - name: Add Docker CE repository
      ansible.builtin.command:
        cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        creates: /etc/yum.repos.d/docker-ce.repo # Makes the task idempotent (won't run if repo file exists)
      changed_when: true # Assume change if command runs (idempotency handled by 'creates')

    - name: Install Docker packages
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Ensure Docker service is started and enabled
      ansible.builtin.systemd:
        name: docker
        state: started # Ensure the service is running
        enabled: true # Ensure the service starts on boot

    - name: Add user to the docker group
      ansible.builtin.user:
        name: "{{ user }}" # Use the shared variable
        groups: docker
        append: true

    - name: Create Docker volume for Portainer
      ansible.builtin.command:
        cmd: docker volume create portainer_data
        creates: /var/lib/docker/volumes/portainer_data

    - name: Run Portainer container
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:lts
        state: started
        restart_policy: always
        published_ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

