---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart nextcloud
  ansible.builtin.command:
    cmd: docker compose up -d
    chdir: "{{ nextcloud_project_dir }}"
  changed_when: true

- name: Reload internal Nextcloud proxy
  ansible.builtin.command:
    cmd: docker compose exec --no-TTY nextcloud-internal nginx -s reload
    chdir: "{{ nextcloud_project_dir }}"
  changed_when: true
