---

- name: Clone vm from template
  import_playbook: clone_vm.yml

- name: Mount ZFS Dataset
  import_playbook: mount-immich-dataset.yml

- name: Setup docker
  hosts: immich
  become: true
  roles: 
    - role: docker_setup
    
- name: Setup portainer
  import_playbook: portainer-setup.yml

- name: Start Immich
  import_playbook: immich-setup.yml

- name: Connect server to tailscale network
  import_playbook: ../common/tailscale-setup.yml
