---
- name: import vaultwarden_backup vars
  ansible.builtin.include_vars:
      file: "../../vaultwarden_backup/defaults/main.yml"

- name: check if vaultwarden directory exists
  ansible.builtin.stat:
    path: "{{ vaultwarden_dir }}/vw_data"
  register: vaultwarden_dir_exists

- name: restore from backup if dir does not exists
  ansible.builtin.import_tasks: restore.yml
  when: not vaultwarden_dir_exists.stat.exists
