- name: Configure syncoid backup on VM
  hosts: proxmox
  become: true
  tasks:
    - name: Copy syncoid backup script to VM
      ansible.builtin.copy:
        src: scripts/syncoid-backup.sh
        dest: /usr/bin/syncoid-backup.sh
        mode: '0775'

    - name: Add syncoid backup script to crontab
      ansible.builtin.cron:
        name: "Run syncoid backup script"
        minute: "0"
        hour: "0"
        job: "/usr/bin/syncoid-backup.sh >> /var/log/syncoid_wdred_cron.log 2>&1"
        state: present
    
    - name: restart cron service
      ansible.builtin.service:
        name: cron
        state: restarted
        enabled: true
