---
- name: Configure AlmaLinux VM User, Directory, and VirtioFS Mount
  hosts: fileserver
  become: true
  vars_files:
    - vars.yml # Include the new variables file

  tasks:

    - name: Create the Samba group
      ansible.builtin.group:
        name: "{{ smb_group }}"
        state: present

    - name: Create the mount point directory
      ansible.builtin.file:
        path: "{{ mount_path }}" # Use the variable for the mount path
        state: directory
        mode: "0755"
        owner: root
        group: "{{ smb_group }}"

    - name: Add VirtioFS entry to /etc/fstab
      ansible.posix.mount:
        path: "{{ mount_path }}" # Use the variable for the mount path
        src: "{{ virtiofs_tag }}" # Use the variable for the VirtioFS tag
        fstype: virtiofs
        opts: defaults
        dump: 0
        passno: 0
        state: present
      notify: Mount filesystems

  handlers:
    - name: Mount filesystems
      ansible.posix.mount:
        path: "{{ mount_path }}" # Use the variable for the mount path
        src: "{{ virtiofs_tag }}" # Use the variable for the VirtioFS tag
        fstype: virtiofs
        state: mounted
      listen: Mount filesystems
