- name: Create the Samba group
  ansible.builtin.group:
    name: "{{ group }}"
    state: present

- name: Create the mount point directory
  ansible.builtin.file:
    path: "{{ share_path }}" # Use the variable for the mount path
    state: directory
    mode: "0775"
    owner: "{{ owner }}"
    group: "{{ group }}"

- name: Add VirtioFS entry to /etc/fstab
  ansible.posix.mount:
    path: "{{ share_path }}" # Use the variable for the mount path
    src: "{{ virtiofs_tag }}" # Use the variable for the VirtioFS tag
    fstype: virtiofs
    opts: defaults
    dump: 0
    passno: 0
    state: mounted
  notify: Mount filesystems