---
- name: Copy script to proxmox
  ansible.builtin.copy:
    src: rename.sh
    dest: /usr/bin/rename.sh
    mode: "0775"

- name: Copy script to proxmox
  ansible.builtin.copy:
    src: exiftool_add_metadata.sh
    dest: /usr/bin/exiftool_add_metadata.sh
    mode: "0775"

- name: Copy script to proxmox
  ansible.builtin.copy:
    src: convert.sh
    dest: /usr/bin/convert.sh
    mode: "0775"