---
- name: Create services VM
  hosts: proxmox
  vars_files:
    - ../secrets.yml
  roles:
    - role: create_template_vm
      tags: create_template_vm

    - role: sanoid_setup
      tags: sanoid_setup

    - role: syncoid_backup
      tags: syncoid_backup
      
    - role: weekly_update
      tags: weekly_update

