- name: Backup couchdb before recreating VM
  hosts: services
  become: true
  gather_facts: false
  vars_files:
    - ../secrets.yml
  tasks:
    - name: Take backup of current couchdb
      ansible.builtin.include_role:
        name: couchdb
        tasks_from: backup.yml
      when: force_recreate | default(false) | bool

    - name: Take backup of vaultwarden database
      ansible.builtin.include_role:
        role: vaultwarden_backup
        tasks_from: backup.yml
      when: force_recreate | default(false) | bool

- name: Create services VM
  hosts: proxmox
  become: false
  vars_files:
    - ../secrets.yml
  vars:
    newid: "{{ vms.services.vmid }}"
    ipaddr: "{{ vms.services.ip }}"
  roles:
    - role: create_vm
      vars:
        create_vm_name: services
        create_vm_newid: "{{ vms.services.vmid }}"
        create_vm_ipaddr: "{{ vms.services.ip }}"
        create_vm_balloon: 2000
        create_vm_cores: 1
        create_vm_memory: 13000
        create_vm_sockets: 1
        create_vm_disk_size: 50G
        create_vm_virtiofs_tag: "{{ virtiofs_tags.smb }}"

  post_tasks:
    - name: add pcie passthrough
      ansible.builtin.include_tasks:
        file: ../misc_tasks/services_pcie_passthrough.yml

- name: Configure services
  hosts: services
  become: true
  vars_files:
    - ../secrets.yml
  vars:
    docker_auto_update_compose_paths:
      - "/home/{{ template.user }}/jellyfin/docker-compose.yml"
      - "/home/{{ template.user }}/nebula-sync/docker-compose.yml"
      - "/home/{{ template.user }}/couchdb/docker-compose.yml"
      - "/home/{{ template.user }}/caddy/docker-compose.yml"
      - "/home/{{ template.user }}/vaultwarden/docker-compose.yml"
    promtail_docker_installed: true
  roles:
    - scheduled_update
    - scheduled_reboot
    - firewall
    - pihole_health
    - nebula_sync
    - syncthing
    - jellyfin
    - couchdb
    - role: couchdb_backup
      tags: couchdb_backup
    - docker_auto_update
    - promtail
    - echovault
    - caddy
    - role: vaultwarden
      tags: vaultwarden
    - role: vaultwarden_backup
      tags: vaultwarden_backup
