# filepath: /home/haaksk/Git/serversetup/playbooks/services.yml
---
- name: Create services VM
  hosts: proxmox # This play runs on the proxmox host
  become: false
  vars_files:
    - ../secrets.yml
  vars:
    target_vm_host: services
  roles:
    - role: create_vm
      tags: create_vm
      vars:
        # Global Proxmox and template variables
        node: "{{ proxmox.node }}"
        api_user: "{{ proxmox.api_user }}"
        clone: "{{ template.name }}" #
        source_vmid_for_clone: "{{ template.vmid }}" 

        # VM-specific variables from hostvars/services.yml
        name: services2
        newid: 4200
        ipaddr: 10.0.0.89
        balloon: 12000
        cores: 2
        memory: 13000
        sockets: 1
        primary_disk_size: 150G
        virtiofs_tag: "{{ virtiofs_tags.smb }}"

- name: Configure services
  hosts: services2
  become: true
  vars_files:
    - ../secrets.yml
  roles:
    - role: mount_virtiofs
      tags: mount_virtiofs
      vars:
        virtiofs_tag: "{{ virtiofs_tags.smb }}"
        mount_path: "/mnt/storage/smb"
    
    - role: docker_setup
      tags: docker_setup

    - role: immich_restore
      tags: immich_restore