- name: Add Pushover tokens to /etc/environment
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "{{ item.key }}='{{ item.value }}'"
    regexp: "^{{ item.key }}="
    state: present
  loop:
    - { key: 'pushover_token_backup', value: '{{ pushover_token_backup }}' }
    - { key: 'pushover_token_immich_dump', value: '{{ pushover_token_immich_dump }}' }
    - { key: 'pushover_token_update', value: '{{ pushover_token_update }}' }
    - { key: 'pushover_user', value: '{{ pushover_user }}' }
  no_log: true 

- name: Copy pushover function to proxmox
  ansible.builtin.copy:
    src: send_pushover.sh
    dest: /usr/local/lib/send_pushover.sh
    mode: "0775"