- name: Rebooting
  ansible.builtin.cron:
    name: "Weekly reboot"
    minute: "0"
    hour: "5"
    month: "*"
    weekday: "7" # 0 for Sunday, 1 for Monday, etc.
    job: "/sbin/reboot"
    user: root # It's best to run a reboot as root

- name: Restart cron service
  ansible.builtin.service:
    name: cron
    state: restarted
    enabled: true
