---
- name: Mount VirtioFS
  hosts: immich
  become: true
  vars_files:
    - vars.yml # Assumes vars.yml contains mount_path and virtiofs_tag

  vars:
    immich_upload_location: "{{ mount_path }}" # e.g., /mnt/storage/immich
    virtiofs_tag: "{{ virtiofs_tag }}" # Tag defined in Proxmox VM hardware

  tasks:
    - name: Ensure VirtioFS mount point directory exists
      ansible.builtin.file:
        path: "{{ immich_upload_location }}"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Add VirtioFS entry to /etc/fstab
      ansible.posix.mount:
        path: "{{ immich_upload_location }}"
        src: "{{ virtiofs_tag }}"
        fstype: virtiofs
        opts: defaults,nofail
        dump: 0
        passno: 0
        state: present
      notify: Mount VirtioFS filesystem

  handlers:
    - name: Mount VirtioFS filesystem
      ansible.posix.mount:
        path: "{{ immich_upload_location }}"
        src: "{{ virtiofs_tag }}"
        fstype: virtiofs
        state: mounted
